services:
  db:
    platform: linux/x86_64
    image: mysql
    container_name: one-month
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_ROOT_USER: root
      MYSQL_DATABASE: one-month
      MYSQL_PASSWORD: password
      TZ: Asia/Seoul